### ISSUE TITLE
help page/wiki

### ISSUE THREAD

**Issue by ganiatgithub** [geronimp/enrichM#77] opened 2019-05-27 23:58 UTC
Hi there,

I cannot look into the information at the help pages/wiki for annotate, classify, etc..

When can that happen?

Cheers

**Comment by geronimp** [comment] 2019-05-28 00:08
Hey Gani,

I'm looking to release those pages soon - hopefully within a week as I'm wrapping up the paper soon.

Sorry for the inconvenience. In the meantime, is there anything you need to know in particular?

Thanks,

Joel

**Comment by ganiatgithub** [comment] 2019-05-28 00:54
Hi Joel,

Thank you for the info, now I understand.
I was trouble-shooting, and realize that I need to rename the .fasta files to .fna in order for the program to recognize it. It seems to be running now.

Cheers

**Comment by geronimp** [comment] 2019-07-10 03:48
Great, I'll close this issue as a duplicate of #17. Thanks again for the bug report

**Closed as completed by geronimp** 2019-07-10 03:48 UTC

**Comment by abhijeetsingh1704** [comment] 2020-01-21 14:45
> Hey Gani,
> 
> I'm looking to release those pages soon - hopefully within a week as I'm wrapping up the paper soon.
> 
> Sorry for the inconvenience. In the meantime, is there anything you need to know in particular?
> 
> Thanks,
> 
> Joel

Is there any documentation/Wiki yet?

**Comment by tvtv195** [comment] 2020-04-20 01:38
Hi Joel, sorry to add this to a thread that's nearly a year old, but it seems we still cannot look into the information at the help pages/wiki for annotate, classify, etc.
